#!/bin/bash

# original docker push command
echo "overwriting docker push $IMAGE_NAME"

cat "node-versions.txt" | while read node_version_line
do
    # The new image tag will include the version of our software, prefixed to the os image we're currently building
    IMAGE_TAG="${DOCKER_REPO}:node-${node_version_line}"

    echo "docker push ${IMAGE_TAG}"
    docker push ${IMAGE_TAG}
done
