version: "3.6"
services:
    restore:
        extends:
            file: docker-compose.yml
            service: restic
        command: 'restore latest:/example-folder --target /example-folder'
        volumes:
            - ./example-folder:/example-folder
            - restic_cache:/root/.cache/restic

volumes:
    restic_cache:
