version: "3"
services:
    backup:
        build:
            context: ./
        image: ambroisemaupate/s3-backup
        env_file: "./.env"
        environment:
            LOCAL_PATH: "/example-folder"
        volumes:
            - ./example-folder:/example-folder:ro
